cedir/web

static/templates/pages/quienes_somos.html

Update en quienes somos

---

static/templates/pages/articulos_profesionales.html
static/templates/pages/educacion_al_paciente.html

Cambios Front-end

---

estudio/imprimir.py
paciente/models.py
static/templates/js/admin/estudio.js

@jiaguilera 
Revisalo cuando puedas, si llega a haber cosas para corregir lo haremos en otra PR ya que necesito mergear esto para manana.

Se arreglan errores en el imprimir estudio

---

estudio/admin.py
estudio/models.py
medicamento/admin.py
medicamento/models.py
medicamento/tests.py
medicamento/views.py
medico/models.py
medico/scripts/borrar_pago_a_medicos.py
turno/views.py

@jiaguilera por favor revisar cuando puedas! Gracias!

Se agrega la app Medicamentos - Se agrega script pago a Medicos

---

medicamento/admin.py
medicamento/models.py
turno/admin.py
turno/models.py

@jiaguilera estos son cambios que me pidieron para controlar el stock de medicamentos desde el admin, mas cambios en info turnos que tambien me pdieron.
revisar cuando puedas! Gracias!

Stock de medicamentos en el admin + cambio en info turnos

---

estudio/imprimir.py

impresión selectiva de pié de página

arregla problema links

---

estudio/imprimir.py

arregla problema linea

---

comprobante/models.py
estudio/models.py
presentacion/admin.py
presentacion/models.py
presentacion/scripts/anular_cobro_presentacion.py
presentacion/tests.py
presentacion/views.py
settings.py.bak
turno/views.py

https://trello.com/c/N7IiJSGM/83-crear-script-que-cancele-un-cobro-de-presentacion
@jiaguilera por favor revisar! Gracias!

Script para anular cobros de presentaciones - se agrega app Presentacion

---

estudio/admin.py
paciente/admin.py
static/templates/js/admin/estudio.js

https://trello.com/c/4ALc6V9s/84-actualizar-plantillas-de-informes-en-el-admin
@jiaguilera

Actualizar plantilla de informes

---

medico/admin.py
medico/models.py

Este PR habilita anestesistas en el admin para agregar y modificar (no eliminar).
@jiaguilera  revisar cuando puedas! Gracias!

Se habilita anestesista en el admin

---

comprobante/imprimir.py

- arregla centrado vertical de líneas en la impresión del comprobante (el mismo problema que teniamos con el centrado del estudio)

Nueva PR para fix de errores

---

medicamento/admin.py
medicamento/models.py

Modificación en el admin de movimientos

---

paciente/models.py
paciente/views.py

Error al crear paciente sin fecha de nac

---

static/templates/js/turno.js
turno/views.py

Se arregla errores al reprogramar y navegar los miercoles y sabados

---

turno/views.py

https://trello.com/c/GQq3UB3M/90-reprogramar-un-turno-no-arrastra-precarga-las-practicas-del-turno-orginal
@jiaguilera revisar cuando puedas! gracias!

Se arregla error al reprogramar no arrastra las practicas

---

static/templates/js/turno.js
static/templates/turnos/buscarTurnosDisponibles.html
turno/models.py

@walterbrunetti recupera los cambios perdidos en el PR #23

muestra el paciente en el detalle

---

static/templates/turnos/buscarTurnosDisponibles.html

@walterbrunetti creo PR para los cambios que me pediste en turnos

Ajustes en turnos

---

static/templates/js/turno.js

Fix Info turnos

---

comprobante/informe_ventas.py

@jiaguilera por favor revisar, gracias!

Se arregla bug en reporte comprobantes

---

anestesista/admin.py
anestesista/calculador_honorarios/calculador_honorarios.py
anestesista/models.py
anestesista/serializers.py
anestesista/views.py
practica/admin.py
practica/models.py

PR asociada de ULI: https://github.com/cedir/uli/pull/9

Cambios Totales Anestesia y Admin Complejidades

---

practica/models.py

Hay que testearlo en staging para ver que ahora no rompa los turnos.

Bugfix: usedLevel

---

medico/admin.py
medico/models.py

https://wiki.postgresql.org/wiki/UPSERT#PostgreSQL_.28today.29
La sección esa de la wiki explica un poco por qué particularmente en PostreSQL queda tan fea la sentencia SQL.
La otra opción era dividir con un if en una sentencia de INSERT y una de UPDATE segun si la instancia de modelo tiene o no clave primaria, pero me pareció mejor tener una sola.
En cuanto a la columna nueva de "matriculaOSDE", se puede agregar por migration (tengo una lista) pero obviamente, solo a tblMedicoAct. Me parece que lo mejor es agregarle la columna a las dos desde pgadmin para estar seguros de que salen iguales.

Alta, busqueda y modificacion de medicos en Django Admin.

---

comprobante/models.py
comprobante/serializers.py
medico/serializers.py

Lo testié localmente en postman y la request contesta correctamente con el id.
Me llama la atención que el campo id no estuviera ya en el model.

agregué el campo id en Comprobante y se lo agregue al serializer

---

comprobante/afip.py
comprobante/tests.py

Work in Progress, pero voy armando la PR.

afip-iter3

---

medico/calculo_honorarios/descuentos.py

Me olvide de cambiar esas constantes en la PR anterior.

cambios en las constantes de los descuentos

---

comprobante/models.py

@QPotato tengo que hacer release de eso urgente porque no pueden imprimir. Te va a traer conflicto con tu branch.

Se arregla error urgente en imprimir FE

---

comprobante/afip.py
comprobante/models.py
comprobante/tests_afip.py
fixtures/comprobantes.json
scripts/tool_testear_afip_contra_webservice.py

En proceso. Todavía no emite. Se queja del tipo de documento o algo.

Factura Electronica MiPyME

---

comprobante/imprimir.py
comprobante/models.py

Agrega el mensaje obligatorio que debe tener las facturas electronicas, ademas de modificar un poco el espacio para que entren nombres de facturas que ocupen dos lineas.
Tambien se agrega el CBU de cedir

Fix comprobante electronico

---

estudio/serializers.py
estudio/views.py

Se agrego como parametro opcional la sucursal en la creacion de un estudio

Post estudios sucursal

---

comprobante/serializers.py
comprobante/tests_informe_contadora.py
estudio/serializers.py
estudio/test_models.py
estudio/tests.py
fixtures/estudios.json
fixtures/medicamentos.json
fixtures/obras_sociales.json
medico/tests.py
obra_social/tests.py
obra_social/views.py
presentacion/serializers.py
presentacion/tests.py
presentacion/views.py

- Importes sugeridos para importe_estudio e importe_medicacion
- Tests para los importes sugeridos
- Fixtures para los test
- Arreglos a los tests que se rompieron por los fixtures nuevos
.
- Se cambia la fecha de las liquidaciones al cerrar presentacion, para
que sea la fecha de la presentacion.
- Se agrega esto a los tests.

Ajustes de APIs Presententacion

---

estudio/tests.py
estudio/views.py
integration_tests/cedir_web.postman_collection.json

Cerre la anterior PR porque intente mergear los cambios de fede y quedo medio quilombo. Asi que abri una nueva y le agregue un par de cosas mas.
Cambios:
- Se separaron las funcionalidades de update importes y pago factura, ahora son endpoints distintos
- Se adapto el codigo al estandar que discutimos en la ultima reunion
- Se corrigen los tests existentes para funcionar con estos endpoints
Falta:
- Integration test de estos endpoints

Update pago contra factura

---

paciente/views.py
static/templates/turnos/buscarTurnosDisponibles.html

Se agrega el campo información extra a la pantalla turnos y se envía un string vacio en caso de que no haya información extra

Campo informacion extra

---

estudio/tests.py
estudio/views.py

- Se saca el filtro por defecto de sucursal
Si el azul nunca llama a este filtro, estaría terminada.
No hay

Sucursal en estudios

---

caja/tests.py
estudio/tests.py
estudio/views.py
medico/views.py
obra_social/views.py
paciente/views.py
presentacion/views.py
requirements-travis.txt
requirements.txt
turno/views.py

- HttpResponse(simplejson(<diccionario>)) deja de funcionar en python3 ya que
HttpResponse pasa a requerir una string binaria y simplejson devuelve
una unicode. Se corrige eso en todo el codigo, estandarizando a
JsonResponse.
- Adicionalmente, se corrigen algunos tests de caja que usaban
simplejson, pasando a usar el json de la libreria estandar de python, para eliminar una dependencia.
En staging. Requiere mucho testing ahí.
No hay.

Python3, 2da iteracion

---

estudio/serializers.py
obra_social/serializers.py

- Se agrega un serializer de la obra social que envía también el valor sugerido de la pensión
Falta probar en staging.
No hay

Valor aproximado pension

---

medicamento/serializers.py

- Se envia en el serializer de medicacion el tipo para estudios
Lista para mergear
No hay

Tipo en medicacion serializer

---

comprobante/informe_ventas.py
comprobante/test_views.py
comprobante/views.py

- Arregla un error del informe de ventas por cambio de bytes a string en el upgrade a Python 3.
- Agrego un Unit Test
Mergeable.
No hay.

Fix informe de ventas, add unit test

---

fixtures/estudios.json
medico/calculo_honorarios/calculador.py
medico/calculo_honorarios/descuentos.py
medico/tests.py

- Refactor de los calculadores de honorarios
- Typing en los calculadores de honorarios
- Algunos tests de logica que faltaban para los calculadores de honorarios
Son muchas lineas pero la mayoria son cambios pavotes.
Mergeable
No hay

Pago Medico 1

---

medico/serializers.py
medico/tests.py
medico/views.py

- Agregué en el serializer de `get_estudios_pendientes_de_pago` los campos que ya están resueltos en el calculador.
- Algunos type hints.
Creería que sí. Así no crece mucho. Falta los del IVA pero que no se como hacerlo y puede ir en otra.
No hay.

PagoMedico 2

---

comprobante/serializers.py
comprobante/tests.py
comprobante/views.py
settings-travis.py

- Se crea un serializer para crear lineas de comprobante
- Se modifica el serializer para crear comprobantes en afip para que acepte varias lineas de comprobante
Faltarian tests, que van a ir en otra PR, por lo que estaria lista para mergear
No hay

Crear comprobantes

---

medico/imprimir_pago.py
medico/serializers.py
medico/views.py

- PDF del pago médico
incompleta. Tengo los datos, falta el formato.
No hay.

Pago Medico 4

---

settings-travis.py

- Se cambian los certificados que utiliza travis
- Lista
No hay

Fix travis

---

comprobante/calculador_informe.py
estudio/models.py
medico/calculo_honorarios/calculador.py
medico/imprimir_pago.py
medico/serializers.py
presentacion/views.py

Comentarios sobre mi codigo antes de irme

---

paciente/serializers.py

- Se agrega como opcional el domicilio del paciente en el paciente serializer
Lista
No hay

Domicilio en paciente serializer

---

obra_social/serializers.py
presentacion/serializers.py
presentacion/tests.py
presentacion/views.py

- se_presenta_por_AMR es enviado en el serializer de obra social
- Se crea el endpoint para refacturar estudios
Lista
No hay

Refacturar estudios y cambios pequeños

---

anestesista/calculador_honorarios/calculador_honorarios.py
anestesista/models.py
anestesista/views.py

Se hace un quick fix con el sin anestesia
Lista
No hay

Fix sin anestesia

---

anestesista/views.py

Se filtra por sucursal
Lista
No

Sucursal en anestesista

---

comprobante/afip.py
estudio/models.py

- Se eliminan los errores que se lanzaban cuando se intentaba visualizar y estaba cobrada la presentacion
- Se intenta arreglar travis
Lista
No hay

Visualizar presentaciones cobradas y fix travis

---

comprobante/imprimir.py
requirements.txt

- Se agrega el qr a la impresion del comprobante
Lista
No hay

QR en imprimir comprobantes

---

presentacion/serializers.py
presentacion/tests.py

- Se actualiza la fecha cobro de los estudios cuando se cobra una presentacion
Lista
Hay migrations? Se fakean o se corren normal?

Cobrar presentacion: Fecha cobro estudios

---

presentacion/imprimir_presentacion.py
presentacion/views.py

Se agregan filtros a presentacion
Lista
No hay

se agregan filtros a presentacion

---

comprobante/serializers.py
comprobante/test_views.py
comprobante/views.py

- Se agregan los filtros de numero de comprobante, cuit y se mejora el filtro del nombre del cliente
Faltaria probarlo junto a la pr de filtros comprobantes en el frontend
No hay

Filtros Comprobantes

---

estudio/models.py
estudio/serializers.py
estudio/tests.py
estudio/views.py
fixtures/estudios.json

- Se agrega el filtro de practica en estudios junto a un test
- Se envia el estado del estudio (Cobrado si esta dado de pago contra factura o en una presentacion cobrada, Pendiente si esta en una presentacion no cobrada y no cobrado si no esta en ninguna presentacion ni esta dado de pago contra factura)
Lista
No hay

Filtro practica en estudios

---

caja/imprimir.py
caja/serializers.py
caja/views.py

- Se crea el imprimir de caja con sus datos correspondientes
Lista. El estilo vendra en la proxima PR
No hay

Imprimir caja it1

---

caja/imprimir.py
caja/serializers.py
caja/tests.py
caja/views.py

- Se aceptan los filtros de caja
- Se muestra el ultimo monto acumulado
- Se agrega la hora de cada movimiento
Falta:
No hay

Imprimir Caja it3

---

turno/tests.py
turno/urls.py
turno/views.py

- Se crea una api para contar turnos
Lista
No hay

Contador turnos

---

caja/tests.py
caja/views.py

- Se reestructuran los filtros de caja
- Se agrega el filtro paciente con su propio test
- Se corrige el filtro de medico que solo consideraba el campo medico del movimiento y no el del estudio
Lista
No hay

Filtros de Caja

---

caja/serializers.py
caja/tests.py

- Se agrega el usuario y la hora a algunos de los serializers de caja
Lista
No hay

Cambios en serializer

---

caja/tests.py
caja/views.py

- Se borra el filtro del medico en caja que busca el medico del estudio
Lista
No hay

Filtro medico

---

caja/imprimir.py
caja/views.py

- Se achica la letra de los movimientos al imprimir
- Se muestra el total
- Se ordenan los movimientos de manera descendente
Lista
No hay

Cambios en imprimir

---

caja/serializers.py
caja/tests.py

- Se remueve el medico del estudio en el serializer de imprimir
Lista
No hay

Caja imprimir sin medico del estudio

---

caja/models.py
caja/serializers.py
caja/tests.py
caja/views.py

- Se crea una función para obtener el monto acumulado correspondiente.
- al modificar un movimiento se actualizan los montos acumulados.
Lista.
No hay.

Caja fix errores

---

.travis.yml
integration_tests/cedir_web_caja.postman_collection.json
integration_tests/local.postman_environment.json

Se agregan integrations tests de caja
Falta corregir algunos tests
No hay

Se agregan integrations tests de caja

---

comprobante/imprimir.py
comprobante/views.py

- Se agrega el mensaje de monotributista al imprimir
Lista
No hay

Mensaje monotributo

---

comprobante/comprobante_asociado.py
comprobante/test_comprobantes_asociados.py
comprobante/views.py

- Se agregan los campos tipo e iva opcionales a la creacion de comprobantes asociados
Lista
No hay

Tipo e iva en comprobantes asociados

---

estudio/tests.py
estudio/views.py

- Se agrega un endpoint para eliminar toda la medicacion de un estudio
Lista
No hay

Eliminar toda la medicacion

---

caja/imprimir.py
estudio/imprimir_listado.py
estudio/serializers.py
estudio/tests.py
estudio/views.py

- Se agrega una api para imprimir el listado de estudios
- Se hace reutilizable la funcion que genera una tabla en imprimir caja
Lista
No hay

Imprimir listado estudios

---

presentacion/serializers.py
presentacion/tests.py

- Los campos de la presentacion solo se actualizan cuando esta abierta
- No se pueden actualizar los campos de una presentacion cobrada
Lista
No hay

Guardar presentacion

---

presentacion/tests.py
presentacion/views.py

- Se implementan filtros ordenables en presentación.
- Se agregan tests de filtros ordenables en presentación.
Lista.
No hay.

Presentación filtros ordenables

---

presentacion/serializers.py
presentacion/tests.py
presentacion/views.py

- Se reemplaza la funcionalidad de cobrar estudios con la de cobro de estudios parcial
- Se mueven los validates del serializar de pago presentacion
- Se realizan tests
Lista
No hay
Hay migrations? Se fakean o se corren normal?

Presentacion - Pago en partes it 2

---

integration_tests/cedir_web.postman_collection.json
integration_tests/facturacion.postman_collection.json
obra_social/serializers.py
obra_social/tests.py
obra_social/views.py
presentacion/tests.py
presentacion/views.py

Cada vez que se quiera buscar los estudios de una nueva presentación o una ya abierta ahora se pasaran con ellos las observaciones de la obra social asociada.
Lista.
No hay.

Obra social pasa observaciones

---

fixtures/estudios.json
fixtures/presentaciones.json
presentacion/serializers.py
presentacion/views.py

- Se arreglan fixture
- Se actualizan los estudios impagos correctamente (antes se actualizaba los importes cobrados, ahora los importes del estudio)
- Se ordenan por numero de comprobante  las presentaciones
Lista. Capaz agregar un test
No hay

Presentacion cobrar en partes 3

---

presentacion/serializers.py

- La cantidad de estudios al cobrar una presentación no puede ser nula.
Lista.
No hay.

Presentación validaciones de estudios al cobrar
